/**
 * karmacv-ws
 * Restful web service for resumes of resumerise app.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: eltonmarku@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class MainTopicItem {
    'categoryType'?: MainTopicItem.CategoryTypeEnum;
    'id'?: string;
    'resumeCategory'?: MainTopicItem.ResumeCategoryEnum;
    'sortOrder'?: number;
    'widgetPackageName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "categoryType",
            "baseName": "categoryType",
            "type": "MainTopicItem.CategoryTypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "resumeCategory",
            "baseName": "resumeCategory",
            "type": "MainTopicItem.ResumeCategoryEnum"
        },
        {
            "name": "sortOrder",
            "baseName": "sortOrder",
            "type": "number"
        },
        {
            "name": "widgetPackageName",
            "baseName": "widgetPackageName",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MainTopicItem.attributeTypeMap;
    }
}

export namespace MainTopicItem {
    export enum CategoryTypeEnum {
        ResumeCategory = <any> 'RESUME_CATEGORY',
        Widget = <any> 'WIDGET'
    }
    export enum ResumeCategoryEnum {
        Awards = <any> 'AWARDS',
        Basics = <any> 'BASICS',
        Certificates = <any> 'CERTIFICATES',
        Education = <any> 'EDUCATION',
        Interests = <any> 'INTERESTS',
        Languages = <any> 'LANGUAGES',
        Projects = <any> 'PROJECTS',
        Publications = <any> 'PUBLICATIONS',
        References = <any> 'REFERENCES',
        Skill = <any> 'SKILL',
        Volunteer = <any> 'VOLUNTEER',
        Work = <any> 'WORK'
    }
}
